### ISSUE TITLE
已退市股票数据缺失

### ISSUE THREAD

**Issue by sailxjx** [chenditc/investment_data#15]
sz000418 这只股票在 csi500 里面

`SZ000418	2012-03-20	2019-06-10`

但是 features 里面没这只股票的数据，2019 年退市

**Comment by chenditc** [comment]
$ ls ~/.qlib/qlib_data/cn_data/features/sz000418 
adjclose.day.bin  amount.day.bin  change.day.bin  close.day.bin  factor.day.bin  high.day.bin  low.day.bin  open.day.bin  volume.day.bin  vwap.day.bin

我看了下是有的
