### ISSUE TITLE
缺少2023-06-09的数据

### ISSUE THREAD

**Issue by qengli** [chenditc/investment_data#18]
导入到qlib后没有2023-06-09的数据，如下图：
<img width="261" alt="image" src="https://github.com/chenditc/investment_data/assets/320935/bef6f93d-7e41-4b3e-aa61-32a76c18f9b9">

查看dolt数据源也是没有，如下图：
<img width="1342" alt="image" src="https://github.com/chenditc/investment_data/assets/320935/34709b61-5c78-4788-be89-8a06920facf9">

上交所和深交所都没有股票数据，倒是有一些北交所的数据

**Comment by redwing4213** [comment]
6月9日的数据是缺失，这种情况频繁发生。

我现在换掘金的数据源了。另外觉得用dolt真不如简单的csv存储分发方便。

**Comment by chenditc** [comment]
确实是缺失了，还挺奇怪的，如果数据不全的话，在 tushare 的 update_a_stock_eod_price_to_latest.py 中应该会查到当日数据不足1000条，会进行补齐才对。

**Comment by chenditc** [comment]
> 6月9日的数据是缺失，这种情况频繁发生。
> 
> 我现在换掘金的数据源了。另外觉得用dolt真不如简单的csv存储分发方便。

我修复06-09的数据之后用 sql 简单查了一下，数据量级从2022年到目前都是合理的4000-5000只股票。您提到这种情况频繁发生是有看到其他什么地方的数据也缺失了么？

**Comment by chenditc** [comment]
现在最新的 release 应该包含了 2023-06-09 的数据了

**Comment by qengli** [comment]
谢谢

**Comment by redwing4213** [comment]
> 

我是指最新一日的数据频繁有缺失。我记得今年4月十几出过一次，4月底又出一次。
第一次好像是某个周五的。周六的数据就好了。
估计依然是数据源更新不及时的问题。
