### ISSUE TITLE
全部遍历了，共缺失1131处数据。

### ISSUE THREAD

**Issue by redwing4213** [chenditc/investment_data#19]
[缺失的数据列表.txt](https://github.com/chenditc/investment_data/files/11733848/default.txt)
[SH601313.csv](https://github.com/chenditc/investment_data/files/11733850/SH601313.csv)
2000年以后只有601313缺失数据了。
附件是掘金导出的601313

**Comment by chenditc** [comment]
谢谢，稍晚的时候我把 601313 的数据导入一下 dolt。

其他缺失的数据点看起来都是 1995年以前的，暂时也没有计划补全，因为 1995 年以前的交易规则和市场情况都很不成熟，对量化帮助也不大。
