### ISSUE TITLE
关于复权价

### ISSUE THREAD

**Issue by quant2008** [chenditc/investment_data#2]
您好，非常感谢您的付出。
有个问题请教，您说：
校验了 A 股历史数据的复权因子。由于浮点数的精度问题，如果相差不大，则不作调整，如果相差大，则找对应的分红或者除权公告进行计算。

实际上，wind的复权方法是最科学的，其他数据源复权方法有问题。所以是不是应该以wind的复权价和复权因子为准，不要“找对应的分红或者除权公告进行计算“自行计算，因为算法可能不对。

**Comment by chenditc** [comment]
校验A股历史数据的复权因子的结果上来看，**目前没有遇到需要调整的情况**。

部分股票的复权因子有区别都是因为浮点数精度问题，例如 复权价 3.3 -> 3.52 时，复权因子会有微小的区别。这部分数据最后我都没有做调整。

计划中 “找对应的分红或者除权公告进行计算” 的原因是，如果当数据真的有比较大区别时，希望可以找到区别的来源是什么，而不是直接套用某一个数据来源的计算结果。我相信 wind 也是有可能出错的，每个数据源都不是完美的。

**Comment by quant2008** [comment]
非常感谢。还有个问题不知我理解对否。
我查看了仓库里最新的数据，如下。在2022-12-01日，只有Tushare表中有最新行情数据。
我的理解是：
1 您的最新行情数据就是用Tushare的，然后用ts_link_table表中基于万德复权价算出的adj_ratio进行调整。
2 每次有股票出现分红配股时，系统都会从wind数据源获取最新复权价来填充ts_link_table
不知以上理解对否？
万德 2019-05-16,SH603801,31.67,30.4,30.63,30.78,31.09,33381.52,103342.698
Tushare 2022-12-01,603042.SH,10.44,10.15,10.16,10.33,10.48495,23858,24562.662

yahoo 2022-07-11,SZ300203,26.3700008392334,24.68000030517578,24.93000030517578,25.760000228881836,25.760000228881836,3.794093e+06
C（caihui） 2019-08-29,SH603639,24.83,24.56,24.83,24.6,35.214,704860

**Comment by chenditc** [comment]
目前增量的数据是直接使用的 tushare 的数据。我没有持续更新的 caihui 和 wind 数据源，所以只对过往数据做了校验。未来我也希望社区有能力帮我加上持续更新的其他数据源来做增量数据的交叉检验。

ts_link_table 表是用于将 tushare 数据转换为最终复权数据的转换比例。有一部分数据是从 caihui 补充来的，他们的就是复权价的绝对值不相等，所以用 adj_ratio 进行调整，但是这个 adj_ratio 对于每个股票来讲是不会变的，比如从 tushare -> final 的过程中，对于同一个股票来说，adj_ratio 是不变的。而从 caihui -> final 的过程中，adj_ratio 也是不变的，但用的是 c_link_table。
