### ISSUE TITLE
特征工程优化的思路

### ISSUE THREAD

**Issue by quant2008** [chenditc/investment_data#21]
您好，非常感谢您的分享。
您在https://mp.weixin.qq.com/s/Athd5hsiN_hIKKgxIiO_ow 提到你做了特征工程优化后，绩效改进较大。
请教您这里特征工程优化的大致思路是什么呢？

**Comment by chenditc** [comment]
主要思路是观察交易策略实际进行交易时，选择交易的触发条件是什么，然后再根据金融行为学的知识去修改特征，使得交易策略更符合预期。
