### ISSUE TITLE
深康佳 SZ000016数据有问题

### ISSUE THREAD

**Issue by quant2008** [chenditc/investment_data#22]
我在[这里](https://www.dolthub.com/repositories/chenditc/investment_data/query/master?active=Tables&q=SELECT+*+FROM++c_a_stock_eod_price++%0AWHERE+symbol%3D%22SZ000016%22+ORDER+BY+tradedate+ASC%3B%0A)执行查询，结果如下，这是深康佳SZ000016的历史行情，数据很不连续，2005年只有一条数据。怎么回事呢？
![image](https://github.com/chenditc/investment_data/assets/116711018/b6bf9489-cdf5-46d4-9b44-df124bdc8598)

**Comment by chenditc** [comment]
c_a_stock_eod_price 只是其中一个数据源。final_a_stock_eod_price 才是经过校验和补充的最终数据源。你可以看 final_a_stock_eod_price 是否有完整的数据。

**Comment by quant2008** [comment]
我使用
SELECT * FROM  final_a_stock_eod_price  
WHERE symbol="SZ000016" and Year(tradedate) = 2005; 系统返回超时。

但是我直接下载您的qlib bin格式数据，看到那段日期有很多na值。

**Comment by chenditc** [comment]
![image](https://github.com/chenditc/investment_data/assets/3244845/88fc6d67-e947-4b53-8eea-e9d53b90b468)

**Comment by acy925** [comment]
> ![image](https://user-images.githubusercontent.com/3244845/257054145-88fc6d67-e947-4b53-8eea-e9d53b90b468.png)
> 
> 我用 qlib 的 features 查看了这个股票 2005 年的数据，没看到有什么问题。可以具体说一下哪一天的数据有缺失吗？以及你对照的其他数据源是哪个？

您好, 我可能遇到了类似的问题, 请教下面第一种命令为什么获得的价格变少了.第二种命令的数目是正确的.
![image](https://github.com/chenditc/investment_data/assets/13726155/ec5b0ae6-b703-4ac8-82ee-fa29b9918bd3)

**Comment by chenditc** [comment]
可以看一下这个股票是不是在 2018年底才调入 csi300 的

**Comment by acy925** [comment]
> 

感谢, 确实是这个问题. 第一命令中,如果不是指数成分就没有交易数据.

**Comment by acy925** [comment]
> 可以看一下这个股票是不是在 2018年底才调入 csi300 的

感谢, 确实是这个问题. 第一命令中,如果不是指数成分就没有交易数据.
