### ISSUE TITLE
关于涨跌幅change

### ISSUE THREAD

**Issue by wenwenzju** [chenditc/investment_data#33]
您好，想请教一下，在 normalize 数据时，调用 qlib 的 yahoo.collector 中的 YahooNormalize.calc_change 计算涨跌幅，用的是没有复权的 close 价格，是不是不合理？是否应该使用复权后的 close 价格？

**Comment by wenwenzju** [comment]
您好，想再请教一个问题，数据在 normalize  之后，open, high, low, close等会进行归一化，即都除以第一日的close，这样的话，在使用qlib回测的时候，使用归一化后的价格进行交易是不是不准确？

**Comment by chenditc** [comment]
qlib 数据集里的 change 是用来计算是否触及涨跌停价格的，不用作回测。这个计算方式并不严谨，所以有 issue 去爬取涨跌停价格来做这个判断：https://github.com/chenditc/investment_data/issues/11

我现在没时间完成这个 issue，你有精力的话可以一起贡献完成。

**Comment by chenditc** [comment]
使用归一化的价格进行交易不会不准确，有疑问的话可以拿一个实际的回测数据，在 qlib 社区反馈。交易回测的逻辑不在这个项目的范畴内。
