### ISSUE TITLE
数据下载后没有分进三个独立文件夹（calendars，instruments, features)

### ISSUE THREAD

**Issue by guoz14** [chenditc/investment_data#34]
目前从github直接下载qlib_bin.tar.gz，本地读取后并没有把files按qlib data要求的三个文件夹分类，而是全都读取到目标路径。9月份的时候，还是分成三个文件夹的。

**Comment by chenditc** [comment]
把 strip-components 改为1 就可以了：

https://github.com/chenditc/investment_data/commit/ea31b1b1c1340ecda02438d8850595657c46ab46

**Comment by guoz14** [comment]
好的，感谢！
