### ISSUE TITLE
每日更新数据延迟

### ISSUE THREAD

**Issue by zhuhuan2004** [chenditc/investment_data#37]
从2024-01-08 开始 Daily update release  qlib_bin 数据都不包含当天的数据，比如 2024-01-08 版本最后交易日数据到 01-05， 01-09 最后交易日数据是 01-08

**Comment by chenditc** [comment]
如果有什么优化方案的话，欢迎提出一起讨论下。

**Comment by zhuhuan2004** [comment]
@duduchu 这是因为数据是归一化以后的

**Comment by duduchu** [comment]
@zhuhuan2004，谢谢了
