### ISSUE TITLE
instruments下的各股票池存在不同规则的分段/分组现象，请问是出于什么考虑，谢谢

### ISSUE THREAD

**Issue by ghyzx** [chenditc/investment_data#38]
大佬们，instruments下的各股票池存在不同规则的分段/分组现象，请问是出于什么考虑，谢谢。

all.txt ： 没有分段与重复，各股票只出现一次；
csi300.txt/csi500.txt/csi800.txt/csi1000.txt/csiall.txt  ： 单个股票出现了多次（次数多样，几次到几十次都有），时间跨度也不同（几个月到半年的都有）；
![csi300](https://github.com/chenditc/investment_data/assets/5229158/ea5db71e-4376-4593-99a8-7e1634f2a37f)

![csi500](https://github.com/chenditc/investment_data/assets/5229158/3f354b46-2f5f-4202-8157-e09b9db6f452)

**Comment by chenditc** [comment]
csixxx 是中证300、800、1000 的股票池。股票调入调处会导致多次出现。这部分可以自行参考 qlib 的文档。
