### ISSUE TITLE
是不是可以共享更多的数据

### ISSUE THREAD

**Issue by markqiu** [chenditc/investment_data#4]
有了您这个项目的基础，咱们可以一起搞一个更大更完整的投资数据共享项目？

**Comment by chenditc** [comment]
@markqiu  是可以的，我的本意就是希望大家在做了数据处理的工作之后可以共享出来。

**Comment by markqiu** [comment]
这个项目就是一个挺好的开始

**Comment by yuhuan1981** [comment]
是不是可以增加Turnover呢？

**Comment by chenditc** [comment]
可以呀，欢迎 Pull Request！
