### ISSUE TITLE
【20240228数据包错误】少了0228这一天的数据

### ISSUE THREAD

**Issue by wscjxky** [chenditc/investment_data#40]
命令复现
wget -N https://github.com/chenditc/investment_data/releases/download/2024-02-28/qlib_bin.tar.gz && tar -xvf qlib_bin.tar.gz -C ~/.qlib/qlib_data/cn_data --strip-components=1

![image](https://github.com/chenditc/investment_data/assets/21272297/0381c8dc-770a-4e91-9914-0240a125fb4b)

**Comment by zhuhuan2004** [comment]
dolt 上今天数据还停留在0227 ，是不是不维护了呢？

**Comment by chenditc** [comment]
Pipeline fixed.
