### ISSUE TITLE
tushare 的 token 到期了，目前不准备续费，暂时停更

### ISSUE THREAD

**Issue by chenditc** [chenditc/investment_data#42]
有人能提供token的话我可以再把更新任务跑起来。需要有至少 2000 积分。

**Comment by dmnsn7** [comment]
Sent to your gmail, plz check.

**Comment by chenditc** [comment]
已经集成进 CI 了，2024-04-13 开始恢复数据更新了。谢谢 @dmnsn7  的 token 支持。
