### ISSUE TITLE
qlib处理过后出来的volume0指标全都是0。

### ISSUE THREAD

**Issue by berisfu** [chenditc/investment_data#47]
![1723338862564](https://github.com/user-attachments/assets/845df408-f107-476f-980a-6589e59d5cdc)

**Comment by chenditc** [comment]
麻烦具体排查一下数据是怎么计算的，如果是计算过程有误，请到 qlib 项目提交 issue。如果是原始数据有误，请具体指出哪一日，哪一个股票的数据有误。
