### ISSUE TITLE
incomplete daily update

### ISSUE THREAD

**Issue by dmnsn7** [chenditc/investment_data#51]
Please note this [dolt commit]( https://www.dolthub.com/repositories/chenditc/investment_data/compare/master/fco73u8g52798l5gp91ru475e8ap35b7), only +1,468 records were added to the final_a_stock_eod_price table.
I think this is caused by lag from TUSHARE side, and the data will be fixed after being refilled.

**Comment by chenditc** [comment]
I revert the commit and reilled the data:

https://www.dolthub.com/repositories/chenditc/investment_data/compare/master/t124r0phba21kmeii5q500m1mroeipk4

Should be good now.

**Comment by dmnsn7** [comment]
@chenditc I notice that [this job](https://github.com/chenditc/investment_data/actions/runs/11342754931/job/31543863261) failed, maybe you can run following commands under your local dolt data folder.
```
dolt reset --hard tq3r2ti0tuug4bn23l1fnqth9qjoie7p
dolt pull
```

**Comment by chenditc** [comment]
> @chenditc I notice that [this job](https://github.com/chenditc/investment_data/actions/runs/11342754931/job/31543863261) failed, maybe you can run following commands under your local dolt data folder.
> 
> ```
> dolt reset --hard tq3r2ti0tuug4bn23l1fnqth9qjoie7p
> dolt pull
> ```

谢谢提醒！确实漏了处理这个任务的缓存区。
