### ISSUE TITLE
dolt pull卡死了

### ISSUE THREAD

**Issue by berisfu** [chenditc/investment_data#52]
![image](https://github.com/user-attachments/assets/145ffec4-d313-4cb3-86af-907e51f98bc0)

发现一直卡死在/ Pulling...

4,092,287 of 10,599,065 chunks complete. 15,933,705 chunks being downloaded currently.
4,092,287 of 10,599,065 chunks complete. 15,933,705 chunks being downloaded currently.
+ cd /dolt/investment_data
+ dolt pull origin

| Pulling...Updating 8ipl4abccin6iqlqf5uvgadohl1o9amn..bec1m9b6vqaveln0u34aafqodek5jtog
- Pulling...commit 8ipl4abccin6iqlqf5uvgadohl1o9amn (HEAD -> master)
Author: Di Chen <chenditc@gmail.com>

- Date:  Mon Oct 14 10:36:15 +0000 2024

        Daily update

- / Pulling...

**Comment by chenditc** [comment]
为了解决这个数据问题，把数据回滚重新更新了一下：https://github.com/chenditc/investment_data/issues/51

所以有一些数据块可能不存在了，要重新 clone 数据

**Comment by chenditc** [comment]
dolt 在海外服务器上都挺快的，dolt 应该底层是存在 aws 的 s3 上。dolt clone 的时候可以挂个海外的代理
